name: Exécuter Poids.ipynb toutes les heures

on:
  schedule:
    # Exécuter toutes les heures à la minute 0 UTC
    - cron: '*/30 * * * *'
  workflow_dispatch:  # pour le lancer manuellement aussi

permissions:
  contents: write  # nécessaire pour pouvoir push via GITHUB_TOKEN

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v4

      - name: Configurer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances nécessaires
        run: |
          pip install pandas numpy scikit-learn scipy seaborn matplotlib torch gspread google-auth jupyter nbconvert papermill

      - name: Exécuter le notebook et écraser le fichier original
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: |
          papermill Poids.ipynb Poids.ipynb

      - name: Commit du résultat
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Poids.ipynb
          git commit -m "Exécution automatique de Poids.ipynb [skip ci]" || echo "Aucun changement à committer"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
